#!/usr/bin/env python
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: MIT
"""
mesh_cluster_tool.py - Cluster mesh vertices using scalar fields and normals.

This script is designed to work as a standalone tool or inside the
3DMeshTracings toolchain. It loads a mesh (PLY/OBJ/etc.), extracts a scalar
field (e.g. the distances generated by the `stacked` pipeline) and optional
features such as vertex normals and coordinates. Features are fed to a
Variational Bayesian Gaussian Mixture Model (VBGMM) to group vertices with
similar behaviour, helping to detect channels or incisions on the mesh.

The script mirrors the I/O conventions of other tools:
  - It tries to use utilities.utilities_io.IOManager and
    utilities.utilities_spatial.GeoLocalizer when available.
  - Falls back to basic Open3D read/write if those utilities are missing.

Example usage:
    python mesh_cluster_tool.py -i C_distances.ply -o clustered --scalar distances \
           --components 5 --include-normals
"""

from __future__ import annotations
import argparse
import sys
from pathlib import Path
import numpy as np

try:
    import open3d as o3d  # type: ignore
except Exception as exc:  # pragma: no cover - handled at runtime
    print(f"[FATAL] open3d not available: {exc}", file=sys.stderr)
    raise

# --- optional utilities -----------------------------------------------------
try:
    from utilities import utilities_io as uio  # type: ignore
except Exception:
    uio = None

try:
    from utilities import utilities_spatial as geo  # type: ignore
except Exception:
    geo = None

try:
    from plyfile import PlyData  # type: ignore
except Exception:
    PlyData = None

from sklearn.mixture import BayesianGaussianMixture

# -------------------------- helpers ----------------------------------------
def load_scalar(path: Path, name: str) -> np.ndarray | None:
    """Return the vertex scalar array from a PLY file."""
    if PlyData is None:
        return None
    try:
        ply = PlyData.read(str(path))
        if "vertex" not in ply.elements:
            return None
        data = ply["vertex"].data
        if name not in data.dtype.names:
            return None
        return np.asarray(data[name])
    except Exception:
        return None


def assemble_features(mesh: o3d.geometry.TriangleMesh,
                      scalar: np.ndarray | None,
                      use_normals: bool = True,
                      use_coords: bool = False) -> np.ndarray:
    feats = []
    if scalar is not None:
        feats.append(scalar.reshape(-1, 1))
    if use_normals:
        if not mesh.has_vertex_normals():
            mesh.compute_vertex_normals()
        feats.append(np.asarray(mesh.vertex_normals))
    if use_coords:
        feats.append(np.asarray(mesh.vertices))
    if not feats:
        raise RuntimeError("No features selected for clustering")
    return np.hstack(feats)


def labels_to_colors(labels: np.ndarray) -> np.ndarray:
    palette = np.array([
        [0, 0, 0], [255, 0, 0], [0, 255, 0], [0, 0, 255],
        [255, 255, 0], [255, 0, 255], [0, 255, 255], [128, 128, 0],
        [128, 0, 128], [0, 128, 128], [200, 200, 200]
    ], dtype=np.uint8)
    return palette[labels % len(palette)]


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser("Cluster mesh vertices by scalar/normals")
    p.add_argument("-i", "--input", required=True, help="Mesh input path (PLY/OBJ/etc.)")
    p.add_argument("-o", "--out-stem", required=True,
                   help="Output stem without extension")
    p.add_argument("--scalar", default="distances",
                   help="Name of scalar field stored in the PLY (default: distances)")
    p.add_argument("--components", type=int, default=3,
                   help="Maximum number of mixture components")
    p.add_argument("--include-normals", action="store_true",
                   help="Include vertex normals as features")
    p.add_argument("--include-coords", action="store_true",
                   help="Include vertex coordinates as features")
    return p.parse_args()


def main() -> int:
    args = parse_args()
    in_path = Path(args.input)
    out_stem = Path(args.out_stem)

    # --- read mesh ---------------------------------------------------------
    mesh = o3d.io.read_triangle_mesh(str(in_path))
    if mesh.is_empty():
        print("[E] input mesh is empty", file=sys.stderr)
        return 2

    # local/global handling (if utilities present)
    anchor = None
    if geo is not None:
        try:
            geoloc = geo.GeoLocalizer()
            mesh = geoloc.to_local_mesh(mesh)
            anchor = geoloc.anchor
        except Exception:
            anchor = None

    scalar = load_scalar(in_path, args.scalar)
    feats = assemble_features(mesh, scalar, args.include_normals, args.include_coords)

    # --- clustering --------------------------------------------------------
    model = BayesianGaussianMixture(n_components=int(args.components), covariance_type="full")
    labels = model.fit_predict(feats)
    colors = labels_to_colors(labels)

    # --- save result -------------------------------------------------------
    # convert to Open3D colors (0..1)
    mesh.vertex_colors = o3d.utility.Vector3dVector(colors.astype(np.float32) / 255.0)

    if uio is not None and hasattr(uio, "IOManager"):
        V = np.asarray(mesh.vertices, dtype=np.float32)
        F = np.asarray(mesh.triangles, dtype=np.int32)
        colors_rgba = np.hstack([colors, np.full((len(colors), 1), 255, np.uint8)])
        io = uio.IOManager(anchor=anchor, crs=None)
        io.save_mesh_bundle(
            out_stem.as_posix(),
            V=V,
            F=F,
            colors_rgba=colors_rgba,
            is_local=False,
            anchor=None,
            save_local=False,
            write_obj=False,
            binary_ply=False,
        )
    else:
        o3d.io.write_triangle_mesh(f"{out_stem}.ply", mesh, write_vertex_colors=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
